### ISSUE TITLE
Question about MakerNotes

### ISSUE THREAD

**Issue by evanoberholster** [dsoprea/go-exif#1]
I read your comment on MakerNote Parsing, any suggestion as to how I could implement it? I looked at the code and couldn't figure it out.

There seems good description of MakerNotes from Phil who built the exiftool in Perl.
https://www.sno.phy.queensu.ca/~phil/exiftool/TagNames/EXIF.html

Thanks

**Comment by dsoprea** [comment]
Sorry. I missed this. 

The problem is that there are a mountain of structures for all of the brands and models of devices that wanted to stash custom data and no standard project to define it all that other projects can consume. So, I'll be moving forward on this in the near future. First, begin implementing all of this in a separate project, and, second, integrate it from this one.

If you're still interested, I can begin implementing and you can contribute in parallel.
