### ISSUE TITLE
Documentation / Example requested for removing EXIF tags from images

### ISSUE THREAD

**Issue by scottleedavis** [dsoprea/go-exif#16]
Hello!

I am writing a plugin for [Mattermost](https://mattermost.com) that automatically strips EXIF tags from uploaded images.  
https://github.com/scottleedavis/mattermost-plugin-noexif

So far, using this library has worked well for reading the tags, but writing back empty or striping out the tags of the files is not straightforward to me yet.

Can this be used to strip out exif tags and if so how?  
Thank you!

**Comment by nimrodshn** [comment]
@scottleedavis Please see: #10

**Comment by scottleedavis** [comment]
Thank you @nimrodshn though from that documentation and link I am still having a hard time seeing how to write the information back to file.  I will do my best but a clear example would help those not familiar with this domain.  :)

**Comment by scottleedavis** [comment]
Hi @dsoprea , I noticed this has been in the TODOs for about a year, and issue #11 & #10 
https://github.com/dsoprea/go-exif/blob/master/TODO#L15-L17

I'd be happy to try to contribute with some guidance.  Also would create the example, (though I am getting ahead of myself here).  :)
https://github.com/scottleedavis/go-exif/blob/issue_16/exif-strip-tool/

**Comment by dsoprea** [comment]
I've just updated the TODO. Those were mostly obsolete.

The idea is to iterate through the IFDs of the existing EXIF information, copying them over one at a time. For each IFD, you just include the tags you specifically want or otherwise don't want to exclude. See [NewIfdBuilderFromExistingChain](https://github.com/dsoprea/go-exif/blob/38a16c885ef7346531c2f5eec5ea7b69d4122f53/ifd_builder.go#L291).

The one thing that we have to be careful of is that there are multiple types of IFD and multiple overlapping tag-IDs between them. It's hokey and dangerous to just take a list of include/exclude tag-IDs and apply them to all of the IFDs recursively. To be done correct, we need to take a "include" list and an "exclude" list of IFD-tag pairs (where a tag should be represented by either an ID *or* a name (in order to be sufficiently useful while also supporting obscure or custom tags), where `NewIfdBuilderFromExistingChain` passes those filters down to `AddTagsFromExisting` (where the filters are applied for the current IFD), which then [recursively] passes them back to [NewIfdBuilderFromExistingChain].

It's a laborious but popular use-case that seems to have a lot of interest, so I'll add a convenience function in the [near?] future to considerably simplify it. See the [dustin/extended_filtering](https://github.com/dsoprea/go-exif/tree/dustin/extended_filtering) branch that I just opened with some notes for this task. If you're feeling up to the task, feel free to work on it.

**Comment by scottleedavis** [comment]
Turns out just decoding and encoding again is enough to stop EXIF for at least jpg and png files using the image lib.   https://github.com/scottleedavis/mattermost-plugin-noexif/blob/master/server/plugin.go

Still interested in seeing how this project handles this but for now going to move forward with the simple solution.

**Comment by philip-firstorder** [comment]
@dsoprea I am starting to implement this library and extract the exif from against more than a +200.000 images, I will give you the status when done.

To change the exif will be the next step, looking forward to your updates.

**Comment by dsoprea** [comment]
Let me know how it goes. I'll double-check things soon, for you.

**Comment by scottleedavis** [comment]
Hi @dsoprea so my solution of decode/encode images to strip of EXIF was rejected in favor of using a proper process to strip only the EXIF tags.  https://github.com/scottleedavis/mattermost-plugin-noexif/issues/2 . Hopefully we can find a solution with go-exif.  :)

**Comment by denieve** [comment]
My colleagues and I have same use case.  Writing back all empty exif is would be very useful to have for us.

**Comment by scottleedavis** [comment]
For JPGS, I am approaching this by extracting the SegmentList, finding the bytes offset and span of the EXIF portion, then reassembling the file without the EXIF bytes.  This approach has a 40% success rate of EXIF removal, on a test set of 100 jpgs.  Still much to improve/change, though it's a start.  I feel the approach of include/exclude tags is cumbersome when the goal in this case is complete removal.

https://github.com/scottleedavis/mattermost-plugin-noexif/pull/4

**Comment by scottleedavis** [comment]
@dsoprea How do you feel about the above approach?  Are there any gotchas/issues you see would arise that I am not considering?

**Comment by scottleedavis** [comment]
I have something now working with 100% accuracy with 80 images.  More testing is needed, however it appears to work as hoped.  The strategy is to use the []byte pattern of the RawExif extracted by go-exif, and then search for it in the image and set the entire region to `0`s.

```go
startExifBytes := StartBytes
endExifBytes := EndBytes

if bytes.Contains(data, mc.RawExif) {
	for i := 0; i < len(data)-len(mc.RawExif); i++ {
		if bytes.Compare(data[i:i+len(mc.RawExif)], mc.RawExif) == 0 {
			startExifBytes = i
			endExifBytes = i + len(mc.RawExif)
		}
	}
	fill := make([]byte, len(data[startExifBytes:endExifBytes]))
	copy(data[startExifBytes:endExifBytes], fill)
}
```
(test run code https://github.com/scottleedavis/go-exif-remove/blob/master/exif_remove.go)

 PNG is next up.  😃

**Comment by scottleedavis** [comment]
going to move forward building a wrapper module.  https://github.com/scottleedavis/go-exif-remove
