### ISSUE TITLE
GPS Coordinates Are Calculated Incorrectly

### ISSUE THREAD

**Issue by keithwoelke** [dsoprea/go-exif#17]
Hello! In the process of trying out this library (thank you, by the way!), I discovered the GPS coordinates are calculated slightly incorrectly.

In ifd_enumerate.go, the values are calculated by dividing the Rationals as expected. However, for some reason, they are truncated instead of stored as float64 types. This causes the value to be off slightly when calculating the final GPS coordinates in degrees.

For example, a Longitude of 77.0365 is returned as [{Numerator:77 Denominator:1} {Numerator:2 Denominator:1} {Numerator:57 Denominator:5}] which calculates as expected by hand, but after the truncating, Decimal() returns it as 77.0363888888889 instead.

**Comment by dsoprea** [comment]
Please clarify what you're referring to when you say "truncating". Please provide a link.

It's not clear what you mean by "a longitude of 77.0365 is returned as..". Since longitudes are represented as rationals in EXIF, they are handled as fractions and degrees but not as decimals (though there are helpers to return these to the user).

Where did you get the longitude that you're using as an example? Did you calculate it by hand from the rationals in a particular image?

**Comment by keithwoelke** [comment]
Apologies for the confusion! I'm referring to the GpsInfo pointer receiver (for Ifd). By truncating, I'm referring to how the rationals are divided as float64 types and then converted to int types. They should be stored in GpsDegrees as float64 types, otherwise, you will potentially lose resolution on your degrees, minutes, and seconds.

https://github.com/dsoprea/go-exif/blob/17eaca42337ccfd5d6ee68eb4208965de383e0c2/ifd_enumerate.go#L904

The longitude of 77.0365 was one I set explicitly on an image, and then calculated using the explicit rationals which are returned by go-exif.

77+(2/60)+(57/5/3600)=77.0365. However, due to the values being stored in GpsDegrees as ints, the final calculation ends up as 77.0363888888889 due to the truncation (as confirmed with the output of the Decimal() method receiver: https://github.com/dsoprea/go-exif/blob/17eaca42337ccfd5d6ee68eb4208965de383e0c2/gps.go#L25).

It does all of its math (correctly) with floats and decimals, but it's working with ints, so it's already doomed to failure. :-)

**Comment by dsoprea** [comment]
Please create a PR. Dont forget to update the tests.

**Comment by lastzero** [comment]
See https://github.com/photoprism/photoprism/issues/21#issuecomment-503853838

You can see the wrong results here: https://demo.photoprism.org/places?q=&lat=&long=&dist=20

Examples: Plants are not in the botanical garden but on the street, clubs are in the water in front of office buildings...

The formula seems right, but maybe Degrees, Minutes, Seconds should be `float`, not `int`?

Compare this libs code with this implementation, which return precise results:

https://github.com/rwcarlsen/goexif/blob/go1/exif/exif.go#L424

We just need to copy & paste and say thanks to the author.

I'd send a PR, but already work 20 h / day and would rather prefer some sleep. If nothing is happening, I'll do it as soon as possible. And thank you for providing this exif library. It's great otherwise, just needs some tweaks to be perfect.

**Comment by lastzero** [comment]
@keithwoelke Thank you! I'll test it now...

**Comment by dsoprea** [comment]
Yeah. Thanks again for catching this.

**Comment by lastzero** [comment]
Looks good to me... plants are back in the garden:

![Screenshot 2019-06-27 at 03 39 28](https://user-images.githubusercontent.com/301686/60226835-36e07080-988d-11e9-885a-c35fe4a6da50.png)

**Comment by dsoprea** [comment]
At first, I thought you were just being metaphorical.
