### ISSUE TITLE
Test results for 200.000 images

### ISSUE THREAD

**Issue by philip-firstorder** [dsoprea/go-exif#22]
Finished implementing go-exif into my project, and tested the first files from 200.000.

Issues found:
- GPS coordinates are shown without minutes and seconds (or decimals). I used the exif-read-tool/main.go code only, without any extra GPSInfo parsing functions.
- Wild west problem with big base64 MakerNote value, these fields will need to be properly parsed in the future
- Found 2 sets of ImageHeight and ImageWidth, same ids but second entries had IfdIndex: 0 set. First entries were the pixel dimensions, second entries had smaller values and it‘s not obvious what they represent

Will post examples in the next days. Stay tuned...

**Comment by dsoprea** [comment]
Thanks for opting to so this. Your location/precision thing is weird. There was a recent change there to account for a loss of precision.

**Comment by philip-firstorder** [comment]
Maybe the change broke something, you could check.
I will also test tomorrow with your sample files and with these:
https://github.com/ianare/exif-samples

**Comment by dsoprea** [comment]
I might not have the immediate chance. I'm traveling. You might also just
try to drop that one commit from the very recent history.

**Comment by philip-firstorder** [comment]
<img width="733" alt="gps without decimals" src="https://user-images.githubusercontent.com/30979663/62417021-bcea9680-b645-11e9-8272-e66ee17515e5.png">

Did a test with your gps sample image and it shows latitude: 26/1 and longitude: 80/1
It should have shown also the minutes and seconds, no?

I don't think it's your latest commit, as you just replaced in with float.

**Comment by philip-firstorder** [comment]
@dsoprea I don't find any Licensing information about this project, can you please specify it?

**Comment by denieve** [comment]
> @dsoprea I don't find any Licensing information about this project, can you please specify it?

Agree.  Most important for downstream projects using this are concerned about.

**Comment by dsoprea** [comment]
Just an oversight. Attached the MIT license just now. I'll look at the above today.

**Comment by dsoprea** [comment]
Ok. Let's ship away at your findings.

From the first posting (https://github.com/dsoprea/go-exif/issues/22#issue-476379771):

- exif-read-tool just displays raw stuff, for debugging. Rational-type values are, by definition, fractions (a "rational" number is a number that can be expressed as a fraction). The GPS coordinates are stored as rational-type values. They're printed as this, too.
- MakerNotes: We don't process maker-note data [yet]. This is data that has a format that's proprietary to the brand/model of the camera. It is enormously complicated to manage this, as we need to embed the structural data for all of the formats that have been reverse-engineered. There are hundreds. I'd rather integrate an exist solution. Since few/none exist in Go, it might have to be implemented. I'm not exist doing this, but I'd rather it be in an separate/independent project that will encourage people to reuse it.
- 2 sets of ImageHeight and ImageWidth: Not sure what image you're talking about. I was unable to find this in my test images. Are you saying that it's a problem with exif-read-tool output or in some existing image's data?

With all of this in mind, please clarify why you think these are bugs (https://github.com/dsoprea/go-exif/issues/22#issuecomment-517955894):

```
There are 2 bugs at exif-read-tool/main.go#L120:

value and valueString are always identical
ResolveAsString function is called with the justFirst parameter set to true
```

**Comment by dsoprea** [comment]
It sounds like there's no issue, here. Let me know if you still perceive there to be an issue.

Since no other issues were mentioned, I've added a mention of you to the README for testing the project with your collection. Thank you for helping.

https://github.com/dsoprea/go-exif/commit/1492e385b5c3ec806940d25e5c8f83edb0c24938

**Comment by philip-firstorder** [comment]
After I tested go-exif on 200.000 files I found out that only about 60% of the total existing metadata was extracted. The problem was the numerous custom fields and camera models that you don't yet support.

I also tested exif-read-tool but it also only supported the standard exif fields, which wasn't enough for my production system.

For production I ended up using [ExifTool](https://exiftool.org/) by Phil Harvey, which is by far the more comprehensive library out there, supports 99% of my metadata formats and provides human readable value translations (even in multiple languages).
The only problem was that it's a Perl Library, if you would translate it in Go would be great, but the library is so big and [releases so often](https://exiftool.org/history.html) that I don't know if it's worth it (I couldn't afford to do it for free).
Phil Harvey also started a C++ version, but it was too much to migrate so it's incomplete. If I were you I would contact him to check if it's feasible to translate it in Go.

Thank you for looking at my issues. I has been great testing it and I would certainly use your library in some future projects.
