### ISSUE TITLE
Few undetected IFDs related to timezone and dimensions

### ISSUE THREAD

**Issue by cajax** [dsoprea/go-exif#30]
Hi!

While testing this lib I found few IFDs that are not recognized -  `9010`, `9011`, `9012` , `a002`, and `a003`.

Here are couple of files for testing purpose https://www.amazon.fr/clouddrive/share/hOMmnLr6fNF89zwQQhqaWHFocKzDdhSBGivOYOXi46V

**Comment by dsoprea** [comment]
I think you mean "tags". IFDs are tag containers. Within the EXIF specification, tags are defined only to appear in a specific IFD. There is a root IFD (confusingly _called_ "IFD"), and it links to one next to it (also the same type). go-exif refers to these as IFD0 and IFD1. IFD0 than has child IFDs called "EXIF" and "GPSInfo", and "EXIF" has a child IFD called "Iop" (Interop).

It looks like these two images are slightly nonconformant. As you said, they both have tags that aren't defined for the IFDs in which they are found:

```
$ go run exif-read-tool/main.go --filepath ~/Downloads/IMG_20200111_111110.jpg 
WARNING: Unknown tag: [IFD] (a002)
WARNING: Unknown tag: [IFD] (a003)
IFD-PATH=[IFD] ID=(0x0100) NAME=[ImageWidth] COUNT=(1) TYPE=[SHORT] VALUE=[4000]
IFD-PATH=[IFD] ID=(0x0101) NAME=[ImageLength] COUNT=(1) TYPE=[SHORT] VALUE=[3000]
IFD-PATH=[IFD] ID=(0x010f) NAME=[Make] COUNT=(8) TYPE=[ASCII] VALUE=[OnePlus]
IFD-PATH=[IFD] ID=(0x0110) NAME=[Model] COUNT=(7) TYPE=[ASCII] VALUE=[GM1913]
...

$ go run exif-read-tool/main.go --filepath ~/Downloads/sample.jpg 
WARNING: Unknown tag: [IFD/Exif] (9010)
WARNING: Unknown tag: [IFD/Exif] (9011)
WARNING: Unknown tag: [IFD/Exif] (9012)
IFD-PATH=[IFD] ID=(0x010f) NAME=[Make] COUNT=(5) TYPE=[ASCII] VALUE=[SONY]
IFD-PATH=[IFD] ID=(0x0110) NAME=[Model] COUNT=(9) TYPE=[ASCII] VALUE=[ILCE-7M3]
IFD-PATH=[IFD] ID=(0x011a) NAME=[XResolution] COUNT=(1) TYPE=[RATIONAL] VALUE=[240/1]
IFD-PATH=[IFD] ID=(0x011b) NAME=[YResolution] COUNT=(1) TYPE=[RATIONAL] VALUE=[240/1]
...
```

It turns out that the 0xa002 and 0xa003 tags are defined for the "EXIF" IFD (see the spec: https://github.com/dsoprea/go-exif/blob/a7bf17d299d4402d3a5cff0023f633187467ed20/assets/DC-008-2012_E.pdf), and, in your images, they are found both in "EXIF" and in "IFD0". Since they aren't defined for "EXIF", those instances can't be identified and are discarded.

In the case of 0x9011, 0x9011, 0x9012, these are non-standard tags. They're not documented in the EXIF specification, so we don't have a choice but to ignore them.

For due diligence, I also ran them through _exif-tool_, and it discards all five as well (though, silently).
