### ISSUE TITLE
 Extracting EXIF tags without storing all bytes in memory

### ISSUE THREAD

**Issue by imclaren** [dsoprea/go-exif#42]
Thanks for creating such a great package.  I created a fork of go-exif/v2 at github.com/imclaren/go-exif that extracts the EXIF tags from files without storing all of the bytes from the start of the EXIF block in memory.  I left all of the existing tests in place and they all still pass.

By default the go-exif scanner searches up to 5MB into the file for the EXIF header, and then scans up to 1MB of EXIF data. These defaults can be changed when creating a new scanner.  I haven't made a pull request because of the substantial changes that I needed to make to go-exif to make this work, but I can if you like.  

Hopefully you find this useful or at least interesting.

**Comment by dsoprea** [comment]
Thanks for exploring this and playing around.

Often the EXIF data appears near the beginning of the image structure. However, why not just allow the brute-force search to scan the entire file? This is not a memory concern.

It sounds like the point of your PR was simply to limit the maximum amount of memory that is allocated. If that is the case, why not just limit the slice that you provide to it (if providing it a byte-slice) or pass an instance of `io.LimitReader` (if providing an `io.Reader`)? What made your change so complicated?

go-exif is inherently a short-lived tool. Pulling-in most of the file isn't much avoidable from the perspective of EXIF parsing because it's a general, addressable space that is itself not inherently structured. Usually reenumerating the data every time you want it would be a bad thing. Once the tags are retrieved (and potentially loaded into a dictionary by the developer), the struct would typically be discarded. So, there's no reason to keep the go-exif structures around.

Most of the time, the EXIF blob is under 4K in size. If there's a thumbnail or two, it may normally be around 50K or 100K in size. There's really no way to avoid putting this blob in memory, as go-exif needs to dereference the value-pointers present for many of the tags. 100K of ephemeral memory usage isn't a concern for most users. If memory is truly limited (for example, if you're needing to extract EXIF on an embedded device that only has a couple of kilobytes of memory), you're somewhat disqualified from using anything but libraries that exclusively use disk-seeks and I'm not sure if any exist.

On a related note, the `IfdEnumerate` type (the main tag-enumeration facility) also includes length estimation. There is a field (with an accessor) that keeps track of the furthest offset read, which might theoretically be used to drop any unnecessary, remaining bytes from the internal slice (if you're naive to the encapsulating format and can't do this more intelligently):

![image](https://user-images.githubusercontent.com/715626/86480662-70f41600-bd1c-11ea-9a5b-1750ddcf6d16.png)

This was an academic change to help debug stuff. There was an issue with a deviant image having a tag with an out-of-bounds issue. This allowed me to identify that some values that were being misinterpreted as addresses and allowed me to determine the range of addresses versus the actual amount of EXIF data.

Once again, a brute-force search will extract all data from the image starting from the EXIF signature until the end of the file, in practice, we'll have exactly as much data as we need. The various image structures will know exactly how big the EXIF blob is, so go-exif won't be loading anything excessive in memory. Note that TIFF images are inherently EXIF blobs (since EXIF derives from the TIFF format), so those tend to be larger. I have also provided JPEG, PNG, HEIF, and TIFF integrations in order to allow efficient EXIF extraction with those formats (see [Scope](https://github.com/dsoprea/go-exif#scope)). The go-exif-knife tool will detect the image format and, if it's one of these, it will use the corresponding project for a targeted extraction. It will fallback to a brute-force search. Given all of this, I don't know if space is ever really a problem for people.

**Comment by imclaren** [comment]
Thanks @dsoprea.

I am running go-exif on a huge set of user files where I don't know (or can't trust) the encapsulating format.  Memory usage is my main constraint, and holding the entire file as a byte slice in memory just to scan for a very small chunk of EXIF data is not an option for me.  I wrote my own disk based file cache because boltdb is too memory thirsty if that gives you an idea of my constraints:  https://github.com/imclaren/calmcache

You're right - just creating a variation of SearchFileAndExtractExif that only sends a limited byte slice to SearchAndExtractExif would do the same thing in a much simpler way.

You are also absolutely right that my intent was to plumb all the way down into go-exif to only hold the required bytes in memory.  I plumbed down to the IfdEnumerate level, but couldn't see a simple way of calculating the maximum size of the remaining byte slice(s) to store in buffers.

Is there a simple way of getting the maximum byte length, rather than just a length estimation, for the IfdEnumerate type?

Also, I added the search limit at the last minute just to speed up processing time for very large files.  I haven't come across any files in my corpus where the EXIF header begins more than 5MB into the file.

**Comment by evanoberholster** [comment]
I faced a similar issue and ended up creating [https://github.com/evanoberholster/exiftool/](https://github.com/evanoberholster/exiftool/). The name of the package will be changing due to confusion with Phil Havey's Exiftool.

**Comment by dsoprea** [comment]
What if I update the underlying data-reading to use a io.ReadSeeker? It should only have to do a few dozen seeks/reads. Shouldn't really have an impact (theoretically).

No. There's no way to know how much data there is without evaluating all of the far value offsets (versus the embedded values). My estimation should be true for every case where there aren't undefined-type tags (read: nonstandard tags) that the library can't parse.

**Comment by imclaren** [comment]
Yes updating the underlying data-reading to use a io.ReadSeeker would resolve the issue.  Thanks again.

**Comment by dsoprea** [comment]
It's a fun idea.

**Comment by dsoprea** [comment]
It's in the "v3" release under the "v3" branch. I'm still adding other backwards-compatible changes to v3 before merging it to master.

**Comment by imclaren** [comment]
Thanks!  I’ll check it out

**Comment by dsoprea** [comment]
Released v3.

**Comment by imclaren** [comment]
Hi - thanks again for this.  I note that SearchAndExtractExifWithReader still does an ioutil.ReadAll, which reads all of the bytes in the file (or io.Reader) from the start of the exif header to the end of the file into memory.

You mention above that there is no way to know how much data needs to be scanned without evaluating all of the far value offsets (versus the embedded values).  Is there a way to do this?  I don't mind if processing is a bit slow.

**Comment by dsoprea** [comment]
No. Although there's an accessor for getting the current value from the IfdEnumerate struct, this will exclude any undefined-type data that we don't support and can't decode. If you don't mind truncating that data in the interest of getting a definite size, you can rebuild new EXIF data from the old data (there's support for that; see the examples). That will drop the unsupported data (e.g. the MakerNotes).
