### ISSUE TITLE
Read EXIF data without loading whole file?

### ISSUE THREAD

**Issue by mholt** [dsoprea/go-exif#5]
Hi there! (Merry Christmas, by the way)

I might be missing it (I'm new to this package), but is there a way to get the EXIF data without reading the whole file into memory? (Imagine several-hundred-MB or even multi-GB video files...)

**Comment by dsoprea** [comment]
Merry Christmas.

I'm assuming that you're referring to one of these functions, which also have explanatory comments:

- [SearchFileAndExtractExif](https://godoc.org/github.com/dsoprea/go-exif#SearchFileAndExtractExif)
- [SearchAndExtractExif](https://godoc.org/github.com/dsoprea/go-exif#SearchAndExtractExif)

1. This is just a convenience function. In order to efficiently parse, you need to provide the EXIF data directly. The other projects ([go-jpeg-image-structure](https://godoc.org/github.com/dsoprea/go-jpeg-image-structure), [go-png-image-structure](https://godoc.org/github.com/dsoprea/go-png-image-structure)), which knows how to parse the specific image formats, to do this for you.
2. What specific video format are you dealing with? No popular video formats support EXIF.

**Comment by mholt** [comment]
Thanks for that tip -- I will look into those packages!

I'm dealing with really _any_ kind of video format (could be in a Google Photos collection, for example) -- mp4 is probably most common.

I'm definitely not an expert on media files or media metadata but am learning quite a lot. I guess if they don't use EXIF I can hunt down another way to get their metadata. :)

Thanks for this package!

**Comment by dsoprea** [comment]
For video formats, you'll likely have to use ffmpeg, gstreamer, etc.. MP4 doesn't support EXIF. Only MOV seems to support EXIF, but, even then, I don't know if it strictly conforms to the spec. It doesn't even seem to have the same, standard EXIF header (well-defined byte order bytes followed by the fixed magic bytes followed by a pointer to the first block of data).

**Comment by mholt** [comment]
Good to know, thank you!
