### ISSUE TITLE
Getting 0x01000000 value for SceneType instead of 0x00000001

### ISSUE THREAD

**Issue by johntrunc** [dsoprea/go-exif#57]
I'm not sure if the library is not parsing well the value or if I need to do some additional parsing of the value. For some reason I'm getting the following value for `SceneType`:

```sh
IFD-PATH=[IFD/Exif] ID=(0xa301) NAME=[SceneType] COUNT=(1) TYPE=[UNDEFINED] VALUE=[0x01000000]
```

For the following image:

![gps](https://user-images.githubusercontent.com/70328146/115251069-75ae7d00-a12a-11eb-9746-d6c55636941c.jpeg)

I'm getting the value `1` using other tools to get Exif data. Not sure if the parsing of the value is made wrong by go-exif or if I should get only the first byte for this specific tag.

Using `v3.0.0` of go-exif.

Thank you.

**Comment by dsoprea** [comment]
So, the issue has to do with the endianness of the file and the allowed values for that field. Note that that field is an UNDEFINED field. Basically, it is a complex (versus simple) stream of bytes that needs to be specifically handled (see undefined/; SceneType is managed by https://github.com/dsoprea/go-exif/blob/master/v3/undefined/exif_A301_scene_type.go). So, certain editors/viewers may not handle them at all. go-exif handles the standard ones (documented in https://github.com/dsoprea/go-exif/blob/master/v3/assets/DC-008-2012_E.pdf).

The SceneType has an official allowed value of (1) with all other values being reserved:

![image](https://user-images.githubusercontent.com/715626/116335151-5b1c7980-a7a4-11eb-99d9-6e7dd583ccaf.png)

Now, your file is big-endian (BE):

```
$ go run command/exif-read-tool/main.go -v -f /tmp/115251069-75ae7d00-a12a-11eb-9746-d6c55636941c.jpeg 
2021/04/27 21:41:05 exif.exif: [DEBUG]  Byte-order is big-endian.
...
IFD-PATH=[IFD/Exif] ID=(0xa217) NAME=[SensingMethod] COUNT=(1) TYPE=[SHORT] VALUE=[[2]]
IFD-PATH=[IFD/Exif] ID=(0xa301) NAME=[SceneType] COUNT=(1) TYPE=[UNDEFINED] VALUE=[0x01000000]
IFD-PATH=[IFD/Exif] ID=(0xa402) NAME=[ExposureMode] COUNT=(1) TYPE=[SHORT] VALUE=[[0]]
```

The issue is that EXIF allows for both little- and big-endianness (LE being the most common). However, even though yours is BE, the value as written would only be read as (1) for LE. In the BE order, it's actually 16777216. So, my guess is that 1) this was incompletely converted by some app that seems to have ignored UNDEFINED-type tags, and 2) since this is an invalid value, it might be getting discarded upon read and just seen as a (1) since that's really the only, officially supported value, anyway. I can't really think of any other alternative explanation.

So, I don't think there's anything I can do. Feel free to provide your thoughts.
