### ISSUE TITLE
Collect goes into an infinite loop for certain exif data

### ISSUE THREAD

**Issue by vansante** [dsoprea/go-exif#59]
I reported this earlier in #56 but the chosen solution was not accepted.

I run a service that extracts certain exif data from user supplied image files. The problem is that for some images this service goes into an infinite loop while extracting and I have traced the source of the problem to this library.

An example image file is this one (zipped to preserve exif data): [broken_exif.zip](https://github.com/dsoprea/go-exif/files/6458604/broken_exif.zip).

When I run the following test code:
```golang
file, err := os.Open("broken_exif.jpg")
if err != nil {
	panic(err)
}
rawExif, err := SearchAndExtractExifWithReader(file)
if err != nil {
	panic(err)
}
ifd, err := exifcommon.NewIfdMappingWithStandard()
if err != nil {
	panic(err)
}
tag := NewTagIndex()
_, _, err = Collect(ifd, tag, rawExif)
if err != nil {
	panic(err)
}
```

The code never returns and remains looping, repeating the same byte offsets over and over again.

**Comment by dsoprea** [comment]
Well, to be clear, the source of the problem is the image. Your previous solution required that the next IFD in a chain had a higher offset than the last, which is not valid. Your issue there (and, presumingly, here) is that your next-IFD pointer seems to point to garbage. The best way of solving this is (a) skipping the file if there's an error (the most intuitive solution), or (b) adding support for an optional behavior for IFD parse failures just skipping and returning.

I'll look into the latter.

**Comment by dsoprea** [comment]
I've managed it by just tracking which IFDs we've seen and then both logging and skipping any IFDs we've already hit.

```
2021/05/12 00:18:49 exif.ifd_enumerate: [WARNING]  Tag (0x0000) is not known and will be skipped.
2021/05/12 00:18:49 exif.ifd_enumerate: [WARNING]  IFD at offset (0x00000048) has been linked-to more than once. There might be a cycle in the IFD chain. Not reparsing.
2021/05/12 00:18:49 exif.ifd_enumerate: [DEBUG]  [IFD1] IFD chain has terminated.
```

**Comment by vansante** [comment]
Yes, the problem is clearly in the image. However, since that is user input you cannot trust it :smile: .

Thanks for looking into and fixing this, much appreciated! :+1:
