### ISSUE TITLE
Returning errors instead of panic

### ISSUE THREAD

**Issue by mholt** [dsoprea/go-exif#6]
I'm quite interested in making heavy use of this package because it's the only one I can find that's pure Go and seems reasonably-recently maintained.

Unfortunately, like the other exif packages I've tried, this package does error handling very non-conventionally and makes it difficult to write stable programs that rely on this package. Instead of just `return err` it does this odd `panic-recover` flow that obscures error values and in many cases, panics aren't recovered.

Stack traces are difficult to follow back because of mulltiple, nested recovered panics (this is from the readme snippet, as fixed in PR #3 - except I use `SearchFileAndExtractExif` instead of `SearchAndExtractExif`:

```
panic: runtime error: index out of range [recovered]
        panic: runtime error: index out of range [recovered]
        panic: runtime error: index out of range

goroutine 21 [running]:
github.com/dsoprea/go-logging.Panic(0x45a7c00, 0xc0006c8a50)
        /Users/matt/Dev/src/github.com/dsoprea/go-logging/log.go:458 +0x79
github.com/dsoprea/go-exif.SearchFileAndExtractExif.func1()
        /Users/matt/Dev/src/github.com/dsoprea/go-exif/exif.go:100 +0x88
panic(0x45a7c00, 0xc0006c8a50)
        /usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/dsoprea/go-logging.Panic(0x45a7c00, 0xc0006c8a50)
        /Users/matt/Dev/src/github.com/dsoprea/go-logging/log.go:458 +0x79
github.com/dsoprea/go-exif.SearchAndExtractExif.func1()
        /Users/matt/Dev/src/github.com/dsoprea/go-exif/exif.go:69 +0x88
panic(0x45a7c00, 0xc0006c8a50)
        /usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/dsoprea/go-logging.Panic(0x45a7c00, 0xc0006c8a50)
        /Users/matt/Dev/src/github.com/dsoprea/go-logging/log.go:458 +0x79
github.com/dsoprea/go-exif.SearchAndExtractExif(0xc0005e4000, 0x770e8, 0x7fe00, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/matt/Dev/src/github.com/dsoprea/go-exif/exif.go:82 +0x126
github.com/dsoprea/go-exif.SearchFileAndExtractExif(0xc00052e0c0, 0x59, 0x0, 0x0, 0x0, 0x0, 0x0)
...
```

I'm willing to submit pull requests, but I'll have to get it working first -- I still haven't been able to get the readme example to work quite yet.

I'm very hopeful for this package though since the only other EXIF library that (mostly) meets my needs hasn't been maintained for months. And even its forks are falling out of maintenance. But it it looks like this package has good tests for reading EXIF data and supports multiple file formats which is :+1:

Assuming I can get this working, is this a change you'd be willing to have merged in, if I revamp the error handling?

**Comment by dsoprea** [comment]
Yeah. That's the reason I wrote it. I wanted and needed something in pure Go and also wanted to specifically support PNG (which offers very new support for EXIF).

My disclaimer for the following is that brute-force EXIF search is just something provided for convenience. It's not efficient (because we search byte-for-byte for the EXIF header) and there's also no way to identify how long the EXIF data is without parsing. So, these functions just return a slice from the header to the end of the file. Obviously, it's much more efficient to parse the JPEG/PNG to get the block of EXIF directly. Not only will that mitigate the issue that you're having (apparently a false positive on the EXIF header search occuring very near to the end of the file), but you'll obviously parse through a gross of images much quicker. See my comments on #5.

This is a fix for not gracefully returning the `ErrNoExif` error in the case mentioned above. You should be fine now (assuming you're just enumerating a bunch of files and correctly managing bad files):

https://github.com/dsoprea/go-exif/commit/bf0b550eff734fb4fd34f2b32107eacad49d6c04

Feel free to share one of more of the problematic images from your corpus if you'd like me too look closer.

All of my projects make heavy use of https://github.com/dsoprea/go-logging and the defer-panic-recover pattern. To print full stacktraces, do a defer-recover at the top like this:

```
	defer func() {
		if state := recover(); state != nil {
			err := log.Wrap(state.(error))
			log.PrintError(err)
		}
	}()
```

This will unbox and print the stacktrace using the obvious functionality that Go doesn't support natively. Obviously, `log` comes from github.com/dsoprea/go-logging. Note that you'll also check for errors using `log.Is()` rather than just simple equalities.

**Comment by dsoprea** [comment]
Let me know if there are any other issues you'd like to debug through.

**Comment by mholt** [comment]
Alright, thanks for the explanation.

**Comment by keithwoelke** [comment]
If the reason for the panic is purely to access a stacktrace, you may also consider https://github.com/pkg/errors instead. :-)

**Comment by dsoprea** [comment]
One more noncontributor who thinks it's prudent to change the direction of development arbitrarily.
