### ISSUE TITLE
Load EXIF without reading the entire file

### ISSUE THREAD

**Issue by sybrenstuvel** [dsoprea/go-exif#65]
Hello,

I want to read EXIF data in my Go code, but the files I use are generally large, around 140 MB per photo. The code I've seen so far (like [exif-read-tool/main.go](https://github.com/dsoprea/go-exif/blob/master/v3/command/exif-read-tool/main.go) and [js_dump/main.go](https://github.com/dsoprea/go-jpeg-image-structure/blob/master/v2/command/js_dump/main.go)) first read the entire file into memory, and then try and interpret the data. Is there any way to pass an `io.ReadSeeker` and only read the data necessary to get to the EXIF?

This question might be more for one of the `go-...-image-structure` projects, it would help me tremendously already to get JPEG and TIFF support in my application. I didn't want to cross-post this question in all the different "image structure" projects, though.

Thanks for any info,
Sybren

**Comment by soypat** [comment]
Lazy loading with a `io.ReaderAt` could do the trick. I implemented exif using lazy loading doing just that here:
https://github.com/soypat/exif

**Comment by dsoprea** [comment]
A brute force search (using go-exif) can iteratively read: https://github.com/dsoprea/go-exif/blob/d21ac8e2de85274733c163a2e1f62d8bb239c31d/v3/utility.go#L112 . The image-specific projects will use the structure of those formats to efficiently extract the EXIF data. Brute-forcing is the only mechanism that go-exif, which is an image-naive project, can, of course, use to find this data.

**Comment by mholt** [comment]
I think there was a comment here suggesting a "lazy-load" approach (or an incremental streaming approach) with an example. Why was that deleted? Was that the same as the `GetFlatExifDataUniversalSearchWithReadSeeker()` function?

**Comment by dsoprea** [comment]
It contributed nothing but referring to another project. I don't believe it mentioned lazy-loading was mentioned because I don't know how that would make sense in this context of file-formats. Rather, if you're not ready to parse it then don't ask to parse it. If you don't know whether there is EXIF data but want to and don't want to just rely on the file-format to indicate whether it's present (if the segment/chunk that usually hosts the EXIF data is present), then parsing is unavoidable.

See above for my comments about efficiently accessing the EXIF data:
https://github.com/dsoprea/go-exif/issues/65#issuecomment-1518671001
