### ISSUE TITLE
unparseable undefined tag - Reloaded

### ISSUE THREAD

**Issue by matthiasbruns** [dsoprea/go-exif#82]
So I've seen there was an issue about this topic before https://github.com/dsoprea/go-exif/issues/47
but the creator did not answer anymore. So I am running into the same issue right now.

For context: My goal is to remove EXIF data which are privacy-related like GPSInfo from existing images.

The code (omitting error handling for the sake of readability)

```go
import (
	"github.com/dsoprea/go-exif/v3"
	exifcommon "github.com/dsoprea/go-exif/v3/common"
)

func cleanEXIF(data []byte) ([]byte, error) {
	rawExif, _ := exif.SearchAndExtractExif(data)

	im, _ := exifcommon.NewIfdMappingWithStandard()

	ti := exif.NewTagIndex()

	_, index, _ := exif.Collect(im, ti, rawExif)

	// build list of paths that need to be deleted
	ifds := index.Ifds
	var toDelete []deletionEntry
	for _, ifd := range ifds {
		// check if the current ifd is allowed
		/// ...
		// example entry looks like this
		// toDelete = append(toDelete, deletionEntry{tagID: 36867, path: "IFD/Exif/ExifIFD/DateTimeOriginal"})
	}

	// prepare mutation of exif data

	// THIS is where the panic is happening
	// panic("unparseable undefined tag")
	rootIb := exif.NewIfdBuilderFromExistingChain(index.RootIfd) ///<----------------- PANIC

	for _, d := range toDelete {
		_ := rootIb.DeleteFirst(d.tagID)
	}

	// generate jpg/png/tiff byte data
	//cleanedData := exportData(...)
	//return cleanedData, nil
}

```

So I understood that there are some weird tags in the image, that cannot be parsed in the chain builder.
I do not understand the api well enough to get around that issue. One idea would be to instead of deleting on existing data, building a new chain based on the allowed tags. Can you give me guidance on how to tackle this? Or maybe there is a non-panic solution to `NewIfdBuilderFromExistingChain`?

You can find the image that is breaking my code in the PR (there are multiple).
![Panasonic_DMC-FZ30](https://github.com/dsoprea/go-exif/assets/1906627/f0c0f105-cfcc-4ccd-81ff-4a0f22951ea6)

**Comment by dsoprea** [comment]
It'd be helpful to share the stacktrace when reporting a panic.

Take a look, here, for how the tree-printer solves this:
https://github.com/dsoprea/go-exif/blob/d21ac8e2de85274733c163a2e1f62d8bb239c31d/v3/ifd_enumerate.go#L921

For convenience (to avoid having to copy, paste, and adjust the enumeration logic as suggested above), we might consider extending the TagIndex type, which owns the identification of all tags and is something that is provided at initialization, with a new flag like `ignoreUnknownTags` or `ignoreUndefinedTags`, and the just skip over tags that aren't in the tags-index or to ignore any 'undefined' ones that we lack the ability to parse, respectively.

Alternatively, an even more elegant solution might be to allow an alternative [tag-parser](https://github.com/dsoprea/go-exif/blob/d21ac8e2de85274733c163a2e1f62d8bb239c31d/v3/ifd_enumerate.go#L211) to be provided or for an optional, interventional callback/filter/predicate to be provided, which would allow you to impose additional semantics. If the tag-parser reads a type it doesn't deem valid or tag not present in the tag-index or it otherwise returns an ErrTagTypeNotValid or ErrTagNotFound error, the tag-parser will just warn and the caller will just skip.

Those might be next steps, but the loop specified at the top should be sufficient for you.
