### ISSUE TITLE
Out of memory when parsing a large file(4G)

### ISSUE THREAD

**Issue by lazyxu** [dsoprea/go-exif#83]
The mov file was shot on the iPhone 13Pro with a duration of 9min 26s and a size of 4G.

When I call the function (exif. SearchAndExtractExifWithReader), the error is out of memory.

![](https://github.com/dsoprea/go-exif/assets/14952805/833fb92c-76e5-417a-8230-8eb4b69716c6)

https://github.com/dsoprea/go-exif/blob/d21ac8e2de85274733c163a2e1f62d8bb239c31d/v3/exif.go#L169

I wonder why we need ioutil.ReadAll, is there no data indicating length in exif.

**Comment by lazyxu** [comment]
I solved this by adding a new struct ReaderSeekerWithDiscarded to replace ioutil.ReadAll. See https://github.com/lazyxu/go-exif/commit/376758eb2e9bf522b3a57a2bd7fd7c520f6b56d4

However, the program is out of memory in the new place
![image](https://github.com/dsoprea/go-exif/assets/14952805/f139d039-fca0-4ee1-87f8-877d63cd8dc0)

Is it because the video (.mov, QuickTime) shot by iPhone has no exif information?
If yes, is there any good way we can filter it?
Sorry I'm a newbie at this.

**Comment by dsoprea** [comment]
So, as mentioned in the README, there is no way of knowing how long the EXIF data is, but typically the outer file-structure can tell us this. That's what the go-image-structure-* projects are four. This are provided for convenience. In your case, if there is no other option than you'd have to find a parser for your MOV in order to first extract the EXIF data and *then* parse it.

Also for convenience, this project provides every conceivable tool to extract the data _if you don't have access to a parser that you can use to first extract the EXIF data_. You're still running out of space because this still works on byte slices instead of dynamically seeking through the data.

Have you tried using [GetFlatExifDataUniversalSearchWithReadSeeker()](https://github.com/dsoprea/go-exif/blob/d21ac8e2de85274733c163a2e1f62d8bb239c31d/v3/utility.go#L112C6-L112C50)? This will simply do a byte-by-byte search for the header, and then try to parse from that point. Note that this is not an efficient solution, but it should be a sufficient last-chance solution that gets the job done if you don't have a smarter way of narrowing the search space.
